{{ $root := . }}
{{- if .Values.chatbot.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $root.Values.global.app_name }}
  namespace: {{ $root.Release.Namespace }}
  annotations:
    gitlab_repository: {{ $root.Values.global.gitlab_repository | quote }}
    commit_sha: {{ $root.Values.global.commit_hash | quote }}
    commit_ref: {{ $root.Values.global.commit_ref | quote }}
    helm.sh/resource-policy: keep
  labels:
    app: {{ $root.Values.global.app_name }}
    app.kubernetes.io/name: {{ $root.Values.global.app_name }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    helm.sh/chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $root.Values.global.app_name }}
  template:
    metadata:
      labels: 
        app: {{ $root.Values.global.app_name }}
    spec:
      containers:
        - name: {{ $root.Values.global.app_name }}
          image: {{ $root.Values.global.chatbot_image_name | quote }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.chatbot.secret_token | quote }}
                  key: BOT_TOKEN
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $root.Values.chatbot.secret_mongodburl | quote }}
                  key: MONGODB_URL
            - name: "deploy_job"
              value: {{ $root.Values.global.job_id | quote }}

            {{ pluck $root.Values.global.env $root.Values.standEnv | first | toYaml | nindent 12 }}

{{- end }}
