{{ $root := . }}
{{- if .Values.chatbot.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $root.Values.global.app_name }}
  namespace: {{ $root.Release.Namespace }}
  annotations:
    gitlab_repository: {{ $root.Values.global.gitlab_repository | quote }}
    commit_sha: {{ $root.Values.global.commit_hash | quote }}
    commit_ref: {{ $root.Values.global.commit_ref | quote }}
    helm.sh/resource-policy: keep
  labels:
    app: {{ $root.Values.global.app_name }}
    name: {{ $root.Values.global.app_name }}
    app.kubernetes.io/name: {{ $root.Values.global.app_name }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    helm.sh/chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
spec:
  selector:
    app: {{ $root.Values.global.app_name }}
  ports:
    #- protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080

{{- end }}