{{ $root := . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.global.app_name }}-env
  namespace: {{ $root.Release.Namespace }}
type: Opaque
stringData:
    {{- range $key, $value := .Values.env }}
    {{ $key }}: {{ $value | quote}}
    {{- end }}