# Стандартная секция PEP(Python Enhancement Proposal) 621
[project]
# Метаданные
name = "targeting-service"
version = "1.0.0"
description = "Targeting Service"
authors = [
    {name = "BMK Team"}
]
requires-python = "==3.12.*"
# Зависимости проекта
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic-settings>=2.1.0",
    "loguru>=0.7.0",
    "peewee>=3.17.0",
    "psycopg2-binary>=2.9.0",
    "httpx>=0.27.0",
    "sqladmin>=0.23.0",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.46",
    "yoyo-migrations>=9.0.0",
    "pytest>=8.0.0",
    "ruff>=0.5,<0.6",
]

[project.scripts]
run = "src.main:main"
migrate = "src.targeting_service.migrate:main"

# Ниже указано, чем собирать пакет: зависимости для сборки и модуль выполнения сборки
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Здесь настройки пакета Hatchling для сборки wheel
[tool.hatch.build.targets.wheel]
packages = ["src"]

# Специфичные опции для uv
[tool.uv]
package = true

# Конфиг ruff: линтер + форматтер
[tool.ruff]
target-version = "py312"
line-length = 100
src = ["src", "tests"]

# Конфиг pytest
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]



